Fix linking against Boost libraries compiled in C++98 mode
Ensure C++ ABI compatibility with Boost libraries compiled in C++98 mode,
which is currently the default for C++ compilers supporting C++11.

libs/log/src/libboost_log.a(text_file_backend.cpp.o): In function `boost::log_mt_posix::sinks::anonymous::file_collector::store_file(boost::filesystem3::path const&)':
libs/log/src/text_file_backend.cpp:673: undefined reference to `boost::filesystem3::detail::copy_file(boost::filesystem3::path const&, boost::filesystem3::path const&, boost::filesystem3::copy_option, boost::system::error_code*)'